using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CQRSProductAPI.Domain.Entities
{

    [Table("AREA_MASTER")]
    public class AreaMaster
    {
        [Key]
        [Column("AREA_ID")]
        [StringLength(10)]
        public string AreaId { get; set; } // Unique ID Generated by System

        [Required]
        [Column("AREA_CODE")]
        [StringLength(10)]
        public string AreaCode { get; set; } // Unique Area Code

        [Required]
        [Column("AREA_NAME")]
        [StringLength(20)]
        public string AreaName { get; set; } // Area Name

        [Required]
        [Column("SHOP_CODE")]
        [StringLength(10)]
        public string ShopCode { get; set; } // Foreign Key

        [Required]
        [Column("PLANT_CODE")]
        [StringLength(10)]
        public string PlantCode { get; set; } // Foreign Key

        [Required]
        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; } // Entry Insertion Date

        [Required]
        [Column("CREATED_BY")]
        public int CreatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_BY")]
        public int UpdatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_DATE")]
        public DateTime UpdatedDate { get; set; } // Updated Date
    }

}
