using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CQRSProductAPI.Domain.Entities
{
    [Table("EQUIPMENT_MASTER")]
    public class EquipmentMaster
    {
        [Key]
        [Column("EQUIPMENT_ID")]
        [StringLength(10)]
        public string EquipmentId { get; set; } // Unique ID Generated by System

        [Required]
        [Column("EQUIPMENT_CODE")]
        [StringLength(10)]
        public string EquipmentCode { get; set; } // Unique Equipment Code

        [Required]
        [Column("EQUIPMENT_NAME")]
        [StringLength(20)]
        public string EquipmentName { get; set; } // Equipment Name

        [Required]
        [Column("ASSET_NO")]
        [StringLength(20)]
        public string AssetNo { get; set; } // Asset No

        [Required]
        [Column("RANK")]
        [StringLength(3)]
        public string Rank { get; set; } // Rank

        [Required]
        [Column("MAKER")]
        [StringLength(20)]
        public string Maker { get; set; } // Maker

        [Required]
        [Column("IMPORT_TYPE")]
        [StringLength(20)]
        public string ImportType { get; set; } // Either Local/Import

        [Required]
        [Column("PLACE")]
        [StringLength(20)]
        public string Place { get; set; } // Place

        [Required]
        [Column("YEAR_OF_INSTALLATION")]
        [StringLength(10)]
        public string YearOfInstallation { get; set; } // Year of Installation

        [Required]
        [Column("AGE")]
        public int Age { get; set; } // Age

        [Required]
        [Column("EQUIPMENT_CATEGORY")]
        [StringLength(20)]
        public string EquipmentCategory { get; set; } // Mention category

        [Required]
        [Column("EQUIPMENT_CATEGORY-01")]
        [StringLength(20)]
        public string EquipmentCategory01 { get; set; } // Mention category01

        [Required]
        [Column("EQUIPMENT_CATEGORY-02")]
        [StringLength(20)]
        public string EquipmentCategory02 { get; set; } // Mention category02

        [Required]
        [Column("STATUS")]
        [StringLength(20)]
        public string Status { get; set; } // Update the status

        [Column("COMMENTS")]
        [StringLength(50)]
        public string? Comments { get; set; } // Free text (optional)

        [Required]
        [Column("STATION_CODE")]
        [StringLength(10)]
        public string StationCode { get; set; } // Foreign Key

        [Required]
        [Column("LINE_CODE")]
        [StringLength(10)]
        public string LineCode { get; set; } // Foreign Key

        [Required]
        [Column("AREA_CODE")]
        [StringLength(10)]
        public string AreaCode { get; set; } // Foreign Key

        [Required]
        [Column("SHOP_CODE")]
        [StringLength(10)]
        public string ShopCode { get; set; } // Foreign Key

        [Required]
        [Column("PLANT_CODE")]
        [StringLength(10)]
        public string PlantCode { get; set; } // Foreign Key

        [Required]
        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; } // Entry Insertion Date

        [Required]
        [Column("CREATED_BY")]
        public int CreatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_BY")]
        public int UpdatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_DATE")]
        public DateTime UpdatedDate { get; set; } // Updated Date
    }

}

