using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CQRSProductAPI.Domain.Entities
{
    [Table("FAULT_MASTER")]
    public class FaultMaster
    {
        [Key]
        [Column("FAULT_ID")]
        [StringLength(10)]
        public string FaultId { get; set; } // Unique ID Generated by System

        [Required]
        [Column("FAULT_MASTER_CODE")]
        [StringLength(10)]
        public string FaultMasterCode { get; set; } // Unique Fault Master Code

        [Required]
        [Column("FAULT_DESCRIPTION")]
        [StringLength(80)]
        public string FaultDescription { get; set; } // Fault Description

        [Required]
        [Column("EQUIPMENT_CODE")]
        [StringLength(10)]
        public string EquipmentCode { get; set; } // Foreign Key

        [Required]
        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; } // Entry Insertion Date

        [Required]
        [Column("CREATED_BY")]
        public int CreatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_BY")]
        public int UpdatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_DATE")]
        public DateTime UpdatedDate { get; set; } // Updated Date
    }

}
