using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CQRSProductAPI.Domain.Entities
{

    [Table("LINE_MASTER")]
    public class LineMaster
    {
        [Key]
        [Column("LINE_ID")]
        [StringLength(10)]
        public string LineId { get; set; } // Unique ID Generated by System

        [Required]
        [Column("LINE_CODE")]
        [StringLength(10)]
        public string LineCode { get; set; } // Unique Line Code

        [Required]
        [Column("LINE_NAME")]
        [StringLength(20)]
        public string LineName { get; set; } // Line Name

        [Column("LINE_DISCRPTION")]
        [StringLength(50)]
        public string LineDescription { get; set; } // Free text

        [Required]
        [Column("AREA_CODE")]
        [StringLength(10)]
        public string AreaCode { get; set; } // Foreign Key

        [Required]
        [Column("SHOP_CODE")]
        [StringLength(10)]
        public string ShopCode { get; set; } // Foreign Key

        [Required]
        [Column("PLANT_CODE")]
        [StringLength(10)]
        public string PlantCode { get; set; } // Foreign Key

        [Required]
        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; } // Entry Insertion Date

        [Required]
        [Column("CREATED_BY")]
        public int CreatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_BY")]
        public int UpdatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_DATE")]
        public DateTime UpdatedDate { get; set; } // Updated Date
    }

}
