using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CQRSProductAPI.Domain.Entities
{
    [Table("MANUAL_MASTER")]
    public class ManualMaster
    {
        [Key]
        [Column("MANUAL_ID")]
        [StringLength(10)]
        public string ManualId { get; set; } // Unique ID Generated by System

        [Column("EQUIPMENT_CODE")]
        [StringLength(10)]
        public string EquipmentCode { get; set; } // Unique Equipment Code

        [Required]
        [Column("MANUAL_CODE")]
        [StringLength(80)]
        public string ManualCode { get; set; } // Unique Manual Code

        [Required]
        [Column("MANUAL_DOCUMNET")]
        public byte[] ManualDocument { get; set; } // Uploaded document (Blob)

        [Required]
        [Column("MANUAL_CATEGORY")]
        [StringLength(20)]
        public string ManualCategory { get; set; } // Manual Category (FMDS/QR/PM)

        [Required]
        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; } // Entry Insertion Date

        [Required]
        [Column("CREATED_BY")]
        public int CreatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_BY")]
        public int UpdatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_DATE")]
        public DateTime UpdatedDate { get; set; } // Updated Date
    }

}
