using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CQRSProductAPI.Domain.Entities
{
    [Table("SHIFT_MASTER")]
    public class ShiftMaster
    {
        [Key]
        [Column("SHIFT_ID")]
        [StringLength(10)]
        public string ShiftId { get; set; } // Unique ID Generated by System

        [Required]
        [Column("SHIFT_CODE")]
        [StringLength(10)]
        public string ShiftCode { get; set; } // Unique Shift Code

        [Required]
        [Column("SHIFT_NAME")]
        [StringLength(20)]
        public string ShiftName { get; set; } // Shift Name

        [Required]
        [Column("SHIFT_CATEGORY")]
        [StringLength(20)]
        public string ShiftCategory { get; set; } // Either Prod/Maintenance/Others

        [Required]
        [Column("SHIFT_START_TIME")]
        public DateTime ShiftStartTime { get; set; } // Start time

        [Required]
        [Column("SHIFT_END_TIME")]
        public DateTime ShiftEndTime { get; set; } // End time

        [Required]
        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; } // Entry Insertion Date

        [Required]
        [Column("CREATED_BY")]
        public int CreatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_BY")]
        public int UpdatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_DATE")]
        public DateTime UpdatedDate { get; set; } // Updated Date
    }

}
