using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CQRSProductAPI.Domain.Entities
{
    [Table("SPARE_MASTER")]
    public class SpareMaster
    {
        [Key]
        [Column("SPARE_ID")]
        [StringLength(10)]
        public string SpareId { get; set; } // Unique ID Generated by System

        [Required]
        [Column("SPARE_CODE")]
        [StringLength(10)]
        public string SpareCode { get; set; } // Unique Spare Code

        [Required]
        [Column("YZA_NUMBER")]
        [StringLength(10)]
        public string YzaNumber { get; set; } // Spare YZA Number

        [Required]
        [Column("EQUIPMENT_CODE")]
        [StringLength(10)]
        public string EquipmentCode { get; set; } // Foreign Key

        [Required]
        [Column("LINE_CODE")]
        [StringLength(10)]
        public string LineCode { get; set; } // Foreign Key

        [Required]
        [Column("AREA_CODE")]
        [StringLength(10)]
        public string AreaCode { get; set; } // Foreign Key

        [Required]
        [Column("SHOP_CODE")]
        [StringLength(10)]
        public string ShopCode { get; set; } // Foreign Key

        [Required]
        [Column("PLANT_CODE")]
        [StringLength(10)]
        public string PlantCode { get; set; } // Foreign Key

        [Required]
        [Column("PART_DESCRIPTION")]
        [StringLength(20)]
        public string PartDescription { get; set; } // Spare Part Description

        [Required]
        [Column("SPECIFICATION")]
        [StringLength(10)]
        public string Specification { get; set; } // Specification

        [Required]
        [Column("STOCK")]
        [StringLength(10)]
        public string Stock { get; set; } // Either STOCK/NONSTOCK

        [Required]
        [Column("QUANTITY")]
        [StringLength(10)]
        public string Quantity { get; set; } // Quantity

        [Required]
        [Column("UOM")]
        [StringLength(10)]
        public string Uom { get; set; } // Unit of Measurement

        [Required]
        [Column("PART_LOCATION")]
        [StringLength(20)]
        public string PartLocation { get; set; } // Part Location

        [Required]
        [Column("SUPPLIER_DETAILS")]
        [StringLength(20)]
        public string SupplierDetails { get; set; } // Logged in User Id

        [Required]
        [Column("MAKER")]
        [StringLength(20)]
        public string Maker { get; set; } // Logged in User Id

        [Required]
        [Column("CATEGORY")]
        [StringLength(15)]
        public string Category { get; set; } // Either Unique/Common

        [Required]
        [Column("IMPORT_TYPE")]
        [StringLength(10)]
        public string ImportType { get; set; } // Either Import/Domestic

        [Required]
        [Column("ESTORE_CATEGORY")]
        [StringLength(15)]
        public string EstoreCategory { get; set; } // Either Local/Technician/SAP

        [Required]
        [Column("EQUIPMENT_WARRANTY")]
        [StringLength(15)]
        public string EquipmentWarranty { get; set; } // Duration of Warranty

        [Required]
        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; } // Entry Insertion Date

        [Required]
        [Column("CREATED_BY")]
        public int CreatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_BY")]
        public int UpdatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_DATE")]
        public DateTime UpdatedDate { get; set; } // Updated Date
    }

}
