using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CQRSProductAPI.Domain.Entities
{
    [Table("SPARE_EQUIPMENT_MAPPINGS")]
    public class SpareEquipmentMapping
    {
        [Key]
        [Column("SPEQ_ID")]
        [StringLength(10)]
        public string SpeqId { get; set; } // Unique ID Generated by System

        [Required]
        [Column("SPARE_CODE")]
        [StringLength(10)]
        public string SpareCode { get; set; } // Spare Code

        [Required]
        [Column("SPARE_YZA_NUMBER")]
        [StringLength(10)]
        public string SpareYzaNumber { get; set; } // Spare YZA Number

        [Required]
        [Column("EQUIPMENT_CODE")]
        [StringLength(10)]
        public string EquipmentCode { get; set; } // Equipment Code

        [Required]
        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; } // Entry Insertion Date

        [Required]
        [Column("CREATED_BY")]
        public int CreatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_BY")]
        public int UpdatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_DATE")]
        public DateTime UpdatedDate { get; set; } // Updated Date
    }

}
