using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CQRSProductAPI.Domain.Entities
{
    [Table("STATION_MASTER")]
    public class StationMaster
    {
        [Key]
        [Column("STATION_ID")]
        [StringLength(10)]
        public string StationId { get; set; } // Unique ID Generated by System

        [Required]
        [Column("STATION_CODE")]
        [StringLength(10)]
        public string StationCode { get; set; } // Unique STATION Code

        [Required]
        [Column("STATION_NAME")]
        [StringLength(20)]
        public string StationName { get; set; } // STATION Name

        [Required]
        [Column("LINE_CODE")]
        [StringLength(10)]
        public string LineCode { get; set; } // Foreign Key

        [Required]
        [Column("AREA_CODE")]
        [StringLength(10)]
        public string AreaCode { get; set; } // Foreign Key

        [Required]
        [Column("SHOP_CODE")]
        [StringLength(10)]
        public string ShopCode { get; set; } // Foreign Key

        [Required]
        [Column("PLANT_CODE")]
        [StringLength(10)]
        public string PlantCode { get; set; } // Foreign Key

        [Required]
        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; } // Entry Insertion Date

        [Required]
        [Column("CREATED_BY")]
        public int CreatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_BY")]
        public int UpdatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_DATE")]
        public DateTime UpdatedDate { get; set; } // Updated Date
    }

}
