using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace CQRSProductAPI.Domain.Entities
{
    [Table("TEAM_MASTER")]
    public class TeamMaster
    {
        [Key]
        [Column("TEAM_ID")]
        [StringLength(10)]
        public string TeamId { get; set; } // Unique ID Generated by System

        [Required]
        [Column("TEAM_CODE")]
        [StringLength(10)]
        public string TeamCode { get; set; } // Unique Team Code O/W/B/G

        [Required]
        [Column("TEAM_NAME")]
        [StringLength(20)]
        public string TeamName { get; set; } // Team Name

        [Required]
        [Column("TEAM_CATEGORY")]
        [StringLength(20)]
        public string TeamCategory { get; set; } // Either Prod/Maintenance/Others

        [Required]
        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; } // Entry Insertion Date

        [Required]
        [Column("CREATED_BY")]
        public int CreatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_BY")]
        public int UpdatedBy { get; set; } // Logged in User Id

        [Required]
        [Column("UPDATED_DATE")]
        public DateTime UpdatedDate { get; set; } // Updated Date
    }

}
